name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    workflow_dipatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      working-directory: web-app
      run:
         docker build . --file Dockerfile --tag blinib1/react.js:$(date +%s)
         docker push blinib1/react.js:$(date +%s)
