name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to dockerhub
      uses: docker/login-action@v1
      with:
        username: blinib1
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - uses: actions/checkout@v2
    - name: Build the Docker image
      working-directory: web-app
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
         docker build . --file Dockerfile --tag blinib1/react.js:$IMAGE_TAG  --tag blinib1/react.js:latest
         docker push blinib1/react.js:$IMAGE_TAG
         docker push blinib1/react.js:latest
